---
  - name: HitBSec Setup
    hosts: all
    become: yes
    become_method: sudo
    become_user: root

    tasks:
      - name: apt-get update
        apt:
          update_cache: yes

      - name: install packages
        apt:
          name: "{{ item }}"
        with_items:
          - python3-dev
          - python3-pip

      - name: update pip
        pip:
          executable: pip3
          name: pip
          extra_args: --upgrade

      - name: install python packages
        pip:
          executable: pip3
          name: "{{ item }}"
        with_items:
          - tensorflow==1.6.0
          - Keras==2.1.5
          - jupyter==1.0.0
          - h5py==2.7.1
          - matplotlib==2.2.0
          - sklearn

  - name: start jupyter notebook
    hosts: all
    tasks:
      - name: start jupyter
        shell: nohup jupyter notebook --ip=0.0.0.0 --NotebookApp.token='' --no-browser </dev/null >/home/vagrant/jupyter.log 2>&1 &
